title: Energy Patterns for Mobile Apps
description: An open catalogue of energy-related patterns in mobile applications
baseurl: "" # empty for local dev; overridden by GitHub Actions
url: "https://tqrg.github.io"

author: Luis Cruz
twitter:
  username: luismcruz

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: pretty

exclude:
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - main.js
  - notes.md
  - old
  - .nojekyll
